// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.30.2
// source: user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SevenCodingTestClient is the client API for SevenCodingTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SevenCodingTestClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type sevenCodingTestClient struct {
	cc grpc.ClientConnInterface
}

func NewSevenCodingTestClient(cc grpc.ClientConnInterface) SevenCodingTestClient {
	return &sevenCodingTestClient{cc}
}

func (c *sevenCodingTestClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.SevenCodingTest/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sevenCodingTestClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/pb.SevenCodingTest/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SevenCodingTestServer is the server API for SevenCodingTest service.
// All implementations must embed UnimplementedSevenCodingTestServer
// for forward compatibility
type SevenCodingTestServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	mustEmbedUnimplementedSevenCodingTestServer()
}

// UnimplementedSevenCodingTestServer must be embedded to have forward compatible implementations.
type UnimplementedSevenCodingTestServer struct {
}

func (UnimplementedSevenCodingTestServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSevenCodingTestServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedSevenCodingTestServer) mustEmbedUnimplementedSevenCodingTestServer() {}

// UnsafeSevenCodingTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SevenCodingTestServer will
// result in compilation errors.
type UnsafeSevenCodingTestServer interface {
	mustEmbedUnimplementedSevenCodingTestServer()
}

func RegisterSevenCodingTestServer(s grpc.ServiceRegistrar, srv SevenCodingTestServer) {
	s.RegisterService(&SevenCodingTest_ServiceDesc, srv)
}

func _SevenCodingTest_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SevenCodingTestServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SevenCodingTest/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SevenCodingTestServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SevenCodingTest_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SevenCodingTestServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SevenCodingTest/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SevenCodingTestServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SevenCodingTest_ServiceDesc is the grpc.ServiceDesc for SevenCodingTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SevenCodingTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SevenCodingTest",
	HandlerType: (*SevenCodingTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _SevenCodingTest_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _SevenCodingTest_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
